### ISSUE TITLE
Reduce the number of playable species

### ISSUE THREAD

**Issue by john-science** [john-science/HCSS#1]
The story requires a living being to start the game.  So that eliminates the undead species:

* mummy
* skeleton
* Jiangshi
* Demonspawn

**Comment by john-science** [comment]
The relevant lines of code appears to be here:  https://github.com/john-science/HCSS/blob/1886dd7e54ed54f9cfa2baff6c7f3b7d5ef9a806/crawl-ref/source/newgame.cc#L197-L201

I guess I would just remove these.

**Comment by PracticalMetal** [comment]
Hi I would like to work on this, can you suggest me ways to get started?

**Comment by john-science** [comment]
> Hi I would like to work on this, can you suggest me ways to get started?

Hello!  So the goal of this fork/game is going to be to create a game where a living hero delves into Hell and smites the devil, or at least some dark angel at the bottom. So, it'll be just a re-work of the regular DCSS game. You only fight undead/demonic enemies, and you can only play one of the good gods, etc.

Have you played DCSS before? That's probably a good place to start, go play Crawl online: https://crawl.kelbi.org/

Other than that, a great place to start would be to build and install the code on your home computer, so you can make changes and re-compile: https://github.com/john-science/HCSS/blob/main/crawl-ref/INSTALL.txt

I see lots of C++ on your profile. So, are you more interested in coding changes, rather than content changes? 

Thanks!

**Comment by john-science** [comment]
> Hi I would like to work on this, can you suggest me ways to get started?

Are you still interested in contributing?

Have you played a roguelike before?
